name: ExpenseTrek
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  encrypt: ^5.0.3
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_cli: ^1.9.1
  shared_preferences: ^2.5.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.17
  pin_code_fields: ^8.0.1
  country_pickers: ^3.0.1
  sms_autofill: ^2.4.1
  intl: ^0.20.2
  pinput: ^5.0.1
  firebase_auth: ^5.5.1
  get_storage: ^2.1.1
  firebase_core: ^3.12.1
#  fluttertoast: ^8.2.12
  smooth_page_indicator: ^1.2.1
  liquid_swipe: ^3.1.0
  flutter_pin_code_fields: ^2.2.0
  http: ^1.3.0
  firebase_messaging: ^15.2.4
  timezone: ^0.10.0
  dots_indicator: ^4.0.1
  multiselect: ^0.1.1
  lottie: ^3.2.0
  states_rebuilder: ^6.4.0
  syncfusion_flutter_charts: ^28.2.9
  curved_navigation_bar: ^1.0.6
  fancy_bottom_navigation: ^0.3.3
  flutter_secure_storage: ^9.2.4
  flutter_slidable: ^4.0.0
  fl_chart: ^0.70.2
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  flutter_pdfview: ^1.4.0
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  flutter_advanced_drawer: ^1.4.0
  mockito: ^5.4.5
  build_runner: ^2.4.15
  file_picker: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.18.0
  win32: ^5.1.1
  responsive_framework: ^0.2.0
  flutter_lints: ^4.0.0
  image_picker:
    path: "./plugins/image_picker-1.1.2"
  image_picker_android:
    path: "./plugins/image_picker_android-0.8.12+22"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/RobotoRomanLight.ttf
        - asset: fonts/PoppinsBold.ttf
    - family: Poppins
      fonts:
        - asset: fonts/PoppinsBold.ttf
