// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS0B1_ng051BEWpf6PIC51S7vtLolgRq8',
    appId: '1:488950901849:web:f985fcfa7783d9d9a99548',
    messagingSenderId: '488950901849',
    projectId: 'expensetrek',
    authDomain: 'expensetrek.firebaseapp.com',
    storageBucket: 'expensetrek.firebasestorage.app',
    measurementId: 'G-1J6S7R5TSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMLkLGc2JhG5w4dMbefDv8807dOwohHkk',
    appId: '1:488950901849:android:19f3793bbb27ae22a99548',
    messagingSenderId: '488950901849',
    projectId: 'expensetrek',
    storageBucket: 'expensetrek.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfcdik2YvR9T6DROcc_BnxDoSJB41mA2A',
    appId: '1:488950901849:ios:9e8de648643ef6e1a99548',
    messagingSenderId: '488950901849',
    projectId: 'expensetrek',
    storageBucket: 'expensetrek.firebasestorage.app',
    iosBundleId: 'com.frutterlabs.financeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfcdik2YvR9T6DROcc_BnxDoSJB41mA2A',
    appId: '1:488950901849:ios:9e8de648643ef6e1a99548',
    messagingSenderId: '488950901849',
    projectId: 'expensetrek',
    storageBucket: 'expensetrek.firebasestorage.app',
    iosBundleId: 'com.frutterlabs.financeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS0B1_ng051BEWpf6PIC51S7vtLolgRq8',
    appId: '1:488950901849:web:5fdad76f8abd6877a99548',
    messagingSenderId: '488950901849',
    projectId: 'expensetrek',
    authDomain: 'expensetrek.firebaseapp.com',
    storageBucket: 'expensetrek.firebasestorage.app',
    measurementId: 'G-KX48RKS66C',
  );
}
